version: '3.6'
services:
  dialogue:
    container_name: dialogue
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c 'yarn install && tsc && pm2-docker start process.dev.json'
    tty: true
    stdin_open: true
    user: node
    environment:
      - NODE_ENV=development
      - TS_NODE_PROJECT=/var/www/tsconfig.json
      - TZ=America/Sao_Paulo
    ports:
      - 3000:3000/tcp
      - 9222:9222/tcp
    networks:
      - dialogue-backend
    working_dir: /var/www
    depends_on:
      - dialogue-mongodb
    volumes:
      - ./:/var/www

  dialogue-mongodb:
    image: mongo:3.4.18-jessie
    container_name: dialogue-mongodb
    stdin_open: true
    tty: true
    ports:
      - 27017:27017/tcp
    networks:
      - dialogue-backend
    volumes:
      - mongodbdata:/data/db

networks:
  dialogue-backend:
    driver: bridge
    ipam:
      config:
        - subnet: 11.11.1.0/24

volumes:
  mongodbdata:
    name: mongodbdata
